---
title: "a02"
author: Sam Samler
Date: 03/03/2026
format: html
---

## Introduction:

My data is from a previous Master's student in Dr. Ichimura's lab group.The data for my research project of nanomechanical properties of tendon fibrils exposed to microgravity conditions. The data contains information on the animal ID, image number on the sampled tendon fibril (and associated jpk ID), the tendon region (calf or quadricep), date sampled, sample type (ground control, spaceflight), average width of tendon fibrils, average height of tendon fibrils, and the Young's Modulus (YM) of the tendon fibrils.

Date Downloaded:03/03/2026

Download source: Excel- Ichimura % Bagley Lab

I will use my data to do statistical analysis of the YM, average width, and average height, of individual tendon fibrils and compare the spaceflight mice with the ground control mice. This will produce conclusions on the impact of spaceflight on connective tissue.

## Data:

I put my data in the raw folder, as it is just raw data with no statistical analysis done yet or data cleaning.

```{r}
install.packages('tidyverse')
TendonData_YM_H_W
```

## Analysis:

This data is tidy in a sense because each column is its own variable, each row is its own observation, and each cell is a single value. The only issue is that the data could be made cleaner by the addition of primary and foreign keys. It could make sense to separate the Sample Number, Condition, Animal ID, and Tendon Origin in a separate table, with Sample Number in both tables acting as a foreign key.

The micrograph column is confusing as well, because it indicates that, for example, Sample 54, had images (3, 4, and 7), that were good enough to process for data analysis, and the number in parentheses (ex: 3(.396)) is the unique image ID generated by the AFM.

Because this is all one table, there are no primary or foreign keys, making it simple but also less concise as you have to sift through a lot of information to get relevant information per sample number and micrograph. As I mentioned above, a second table containing the specifics of the Sample Number and where it came from, condition, origin, etc would be better for analysis purposes.
